<script>
	// Promesa fulfilled con datos incorrectos se arroja error y cae en catch

	const myPromise = new Promise((resolve, reject) => resolve(1))

	myPromise
		.then(result => {
			if (result !== 2) throw new Error("Tremendo error")
			console.log(result)
		})
		.catch(error => console.log(error))
</script>
